### ISSUE TITLE
Duplicate node activation 

### ISSUE THREAD

**Issue by juandpenan** [jmguerreroh/perception_system#13]
I think [this](https://github.com/jmguerreroh/perception_system/blob/58bc901c0e3df38beec3c492c9b8a0124684786b/perception_system/src/perception_system/PerceptionListener.cpp#L150) and [this](https://github.com/jmguerreroh/perception_system/blob/58bc901c0e3df38beec3c492c9b8a0124684786b/perception_system/src/perception_system/PerceptionListener.cpp#L162) should be objects instead of people

**Comment by jmguerreroh** [comment]
Totally agree, sorry for the mistake.
