### ISSUE TITLE
New branch requested

### ISSUE THREAD

**Issue by juandpenan** [jmguerreroh/perception_system#18]
Hi Mr Dr @jmguerreroh  I would like to kindly ask you if it is possible to create a new branch named jazzy or related so I can summit a PR with the compiling version for that ROS distro. 

Thank you in advance!

**Comment by jmguerreroh** [comment]
Hey @juandpenan, let’s get jazzy! 

I created a new branch so you can submit your PR with the compiled version for the ROS distribution. Thank you for contributing and helping us maintain compatibility with the latest features.

Regards :)
